### ISSUE TITLE
algorithm issue

### ISSUE THREAD

**Issue by rcchilders** [OuhscBbmc/usnavy-billets#3]
1.  any chance we can use names instead of officer codes?  Might decrease the chance of human error...
2.  The inputs seem to be accurate, but the algorithm results as I read them don't seem correct.
Here are some examples:
a.  CBIRF (215) ranked 425 #1, and 425 ranked CBIRF (215) #1 but no match was made.
b.  NMCP (209) ranked 427 #1, and NMCP (209) ranked him #5 (and they have 6 billets) but no match was made.
c.  NMCP (209) ranked 420 #1, and 420 ranked nmcp (209) #1, but no match was made
d.  Jax (210) ranked 414 #1, and 414 ranked 210 #1, but no match was made.

**Comment by wibeasley** [comment]
thanks @rcchilders for sniffing this out.  I'll check it out tonight.  My leading suspect is that the mapping between 'index' and 'id' got corrupted during the most recent changes.

**Comment by wibeasley** [comment]
@rcchilders, after our phone call last night and your email this morning, I believe this has been resolved.  Please reopen the issue if you'd like.
