### ISSUE TITLE
Small example

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/usnavy-billets#4]
To understand #3 better, I'm creating a smaller example. in the sandbox.  My current guess is that the problem's related to the matrix orientation.  It looks like I'm passing the matrified-dataset, but the transpose occurs *after* it was matrified, not *before*.

(cc: @rcchilders)

**Comment by wibeasley** [comment]
@rcchilders 

I'm thinking that college 1 should be matched with student 3 (but it was matched with student 1 instead).  Student 3 ranked the college first (ie, `s.prefs.smi[1,3]`), while college 1 ranked student 3 first
(ie, `c.prefs.smi[3,1]`).

```
> m
$s.prefs.smi
     [,1] [,2] [,3] [,4]
[1,]    2    3    1    3
[2,]    1    1    3    1
[3,]    3    2    2    2

$c.prefs.smi
     [,1] [,2] [,3]
[1,]    2    2    1
[2,]    3    4    3
[3,]    1    3    4
[4,]    4    1    2

$matchings
  matching college student sOptimal cOptimal
1        1       1       2        1        1
2        1       2       4        1        1
3        1       3       1        1        1
```

**Comment by rcchilders** [comment]
took me a awhile, but I agree.
Student #4/college 2 worked out.
I need to look at it some more.
This is easier than looking at 50!

**Comment by wibeasley** [comment]
@rcchilders, I tried another R package (called [matchingR](https://github.com/jtilly/matchingR/)) and got the same result, for better or for worse.  Despite command 1 and officer 3 ranking each other first, they're not matched (furthermore three goes unmatched).

```
> matchingR::galeShapley.collegeAdmissions(
+   collegePref = command_transition,
+   studentPref = officer_transition 
+ )
$unmatched.students
[1] 3

$unmatched.colleges
numeric(0)

$matched.colleges
     [,1]
[1,]    2
[2,]    4
[3,]    1

$matched.students
     [,1]
[1,]    3
[2,]    1
[3,]   NA
[4,]    2
```

**Comment by rcchilders** [comment]
Hmm.  Contact AL?

**Comment by wibeasley** [comment]
@rcchilders, I think we solved this.  I can explain more on the phone when you call.  In short, I was feeding it something like a 'negative utility matrix', instead of the 'preference matrix'.   The format, order, & notation are slightly different.  The next task is #5.
