### ISSUE TITLE
Installing on Red Hat

### ISSUE THREAD

**Issue by bradbell** [OuhscBbmc/usnavy-billets#8]
How does on run the tests for this program starting with a clone of the repository ?

**Comment by wibeasley** [comment]
Hi @bradbell, which tests are you referring to?  The R package checks are most easily run within RStudio w/ ctrl-shift-e.

Before that, there are several options for getting the code and (de-identified) dataset on your local machine to run.  One way is to download the most recent version of the files as a [zip](https://github.com/OuhscBbmc/usnavy-billets/archive/master.zip) from the "Clone or download" green button on the repo home page.  Another way is to "Fork" the repo to your own control; the Fork button is in the top right of the repo webpage.

I don't know what your background is, so this may not be the info you'd like.  Tell me if not.

**Comment by bradbell** [comment]
I have a clone of the repository on a unix system in the directory
     usnavy_billets.git
I then execute the commands:
    R CMD BATCH --quiet tests/test-all.R test-all.out
    cat test-all.out
and get the result:
> #Modeled after the R6 testing structure: https://github.com/wch/R6/blob/master/tests/testthat.R
> library(testthat)
Error in library(testthat) : there is no package called ‘testthat’
Execution halted

**Comment by wibeasley** [comment]
@bradbell, I've added more installation information.  Does this help?  Tell me if not, because others might have the same question.

If you're installing on Linux, the rJava dependency will probably be the trickiest.

**Comment by bradbell** [comment]
I get errors during the command
remotes::install_github(repo="thiloklein/matchingMarkets")

The first one is
* installing *source* package ‘gmp’ ...
** package ‘gmp’ successfully unpacked and MD5 sums checked
creating cache ./config.cache
checking for __gmpz_ui_sub in -lgmp... no
configure: error: GNU MP not found, or not 4.1.4 or up, see http://gmplib.org
ERROR: configuration failed for package ‘gmp’
* removing ‘/home/bradbell/R/x86_64-redhat-linux-gnu-library/3.4/gmp’

When I check for gmp on my system i get version 6.1.2:
usnavy_billets.git>dnf info gmp
Last metadata expiration check: 0:01:54 ago on Fri 30 Mar 2018 06:33:24 AM MST.
Installed Packages
Name         : gmp
Epoch        : 1
Version      : 6.1.2
Release      : 4.fc26
Arch         : x86_64
Size         : 614 k
Source       : gmp-6.1.2-4.fc26.src.rpm

**Comment by wibeasley** [comment]
If I'm reading your error message correctly, you're getting stuck on the R package, [gmp](https://CRAN.R-project.org/package=gmp).  Which is a dependency of matchingMarkets, which is a dependency of my package.  It looks like you installed the linux gmp package with the second message you pasted, which I agree is the right thing to do.

All that sounds correct to me, but I'm sorry I've never tried installing it on Red Hat, so I don't have more ideas.

From gmp's CRAN page, it reference's the package's [development site](http://mulcyber.toulouse.inra.fr/projects/gmp).  Consider asking them for advice with your configuration.  Sorry I don't have more experience with your configuration.

**Comment by bradbell** [comment]
Looking at
>   https://github.com/thiloklein/matchingMarkets
I could see the problem with gmp was that I needed to install gmp-devel:
>    sudo dnf install gmp-devel
Once I did the following install worked:
>   remotes::install_github(repo="thiloklein/matchingMarkets")
After this I did the 
    remotes::install_github(repo="OuhscBbmc/usnavy-billets", dependencies=TRUE)
which seemed to bring in alot of other packages with no errors in the output and
  * DONE (USNavyBillets)
near the end of the output.

Now when i execute
    R CMD BATCH --quiet tests/test-all.R test-all.out
I get

usnavy_billets.git>cat test-all.out
> #Modeled after the R6 testing structure: https://github.com/wch/R6/blob/master/tests/testthat.R
> library(testthat)
> library(USNavyBillets)
> 
> testthat::test_check("USNavyBillets")
Error: No tests found for USNavyBillets
Execution halted
usnavy_billets.git>

**Comment by wibeasley** [comment]
@bradbell, I don't know anyone who runs tests from the command line, outside of R.  Running inside of RStudio is the typical approach: http://r-pkgs.had.co.nz/tests.html#test-workflow.

**Comment by bradbell** [comment]
The problem was setting the working directory. If  I execute the commands:

> cd tests
> R CMD BATCH --quiet test-all.R test-all.out
> cat test-all.out

I get the result

> #Modeled after the R6 testing structure: https://github.com/wch/R6/blob/master/tests/testthat.R
> library(testthat)
> library(USNavyBillets)
> 
> testthat::test_check("USNavyBillets")
══ testthat result ════════════════════════════════════════════════════
OK: 2 SKIPPED: 0 FAILED: 0
> 
> proc.time()
   user  system elapsed 
  0.864   0.034   0.898 

I summary, the tests seem to be running and passing.  Do you know what the 2 skipped is about ?
Thanks

**Comment by wibeasley** [comment]
I'm glad it's running now for you.  There's a chance you're misreading the output.  I see zero skipped (as well as two passed and zero failed).

after inserting line breaks, I see
OK: 2
SKIPPED: 0
FAILED: 0

**Comment by bradbell** [comment]
I see, that makes sense. Thanks again !
